const productData = [
  {
    id: 1,
    imageUrl: "/assets/images/img1.png",
    title: "Tentron modular sofa_3",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 2,
    imageUrl: "/assets/images/img2.png",
    title: "Granite dining table with dining",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 3,
    imageUrl: "/assets/images/img3.png",
    title: "Outdoor bar table and stool",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 4,
    imageUrl: "/assets/images/img4.png",
    title: "Plain console with teak mirror",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 5,
    imageUrl: "/assets/images/img5.png",
    title: "Tentron modular sofa_3",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 6,
    imageUrl: "/assets/images/img6.png",
    title: "Granite dining table with dining",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 7,
    imageUrl: "/assets/images/img7.png",
    title: "Outdoor bar table and stool",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 8,
    imageUrl: "/assets/images/img8.png",
    title: "Plain console with teak mirror",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 9,
    imageUrl: "/assets/images/img5.png",
    title: "Tentron modular sofa_3",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 10,
    imageUrl: "/assets/images/img6.png",
    title: "Granite dining table with dining",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 11,
    imageUrl: "/assets/images/img7.png",
    title: "Outdoor bar table and stool",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 12,
    imageUrl: "/assets/images/img8.png",
    title: "Plain console with teak mirror",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 13,
    imageUrl: "/assets/images/img5.png",
    title: "Tentron modular sofa_3",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 14,
    imageUrl: "/assets/images/img6.png",
    title: "Granite dining table with dining",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
  {
    id: 15,
    imageUrl: "/assets/images/img7.png",
    title: "Outdoor bar table and stool",
    price: "Rs. 25,000.00",
    description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound",
  },
];

export default productData;
